const studentWild = [
    {
        firstName: 'Geoffrey',
        lastName: 'Leglise',
        promo: 'DevWeb',
        birthDate: '03/03/1995',
        github:'https://github.com/gleglise',
        linkedin:'https://fr.linkedin.com/in/geoffrey-leglise',
        hobbies:'Jeux Videos, Musique, Tech',
        proObjective:'Développeur Web.',
        quote:'“Il y a du bon dans ce monde, et il faut se battre pour y arriver. ”',
        image: 'images/photoWilders/dev/geoffreyL.jpg',
    },
    {
        firstName: 'Julien',
        lastName: 'Cartron',
        promo: 'DevWeb',
        birthDate: '12/09/1994',
        github:'https://github.com/Wakoz',
        linkedin:'https://www.linkedin.com/in/julien-cartron-747559330/',
        hobbies:'Jeux Videos,Musique',
        proObjective:'Obtenir une alternance a la suite de mon titre',
        quote:"",
        image: 'images/photoWilders/dev/julienC.jpg',
    },
    {
        firstName: 'Sarah',
        lastName: 'Smandack',
        promo: 'DevWeb',
        birthDate: '08/01/1997',
        github:'https://github.com/sarah-sdk',
        linkedin:'https://fr.linkedin.com/in/sarah-smandack-161419167',
        hobbies:'Jeux videos, manger',
        proObjective:'Travailler de là où je veux',
        quote:`"C'est l'hopital qui se fiche du beurre de karité."`,
        image: 'images/photoWilders/dev/sarahS.jpg',
    },
    {
        firstName: 'Marwane',
        lastName: 'Ben Khalifa',
        promo: 'DevWeb',
        birthDate: '25/03/1997',
        github:'https://github.com/Makenchii',
        linkedin:'https://fr.linkedin.com/in/marwane-ben-khalifa',
        hobbies:'Sport',
        proObjective:'Alternance',
        quote:'« Vide ton esprit, sois informe. Informe, comme l’eau. » Bruce Lee',
        image: 'images/photoWilders/dev/marwaneB.jpg',
    },
    {
        firstName: 'Sybill',
        lastName: 'Gribonval',
        promo: 'TSSR',
        birthDate: '08/01/1992',
        github:'https://github.com/Mirhazka',
        linkedin:'https://www.linkedin.com/in/sybill-gribonval-0ab964165/',
        hobbies:'Jeux vidéo & Manga',
        proObjective:'',
        quote:'',
        image: 'images/photoWilders/tssr/sybillG.jpg',
    },
    {
        firstName: 'Nino',
        lastName: 'Jautee',
        promo: 'DevWeb',
        birthDate: '09/01/1997',
        github:'https://github.com/NinoDiving',
        linkedin:'https://www.linkedin.com/in/nino-jautee-aa2723321/',
        hobbies:'Plongée sous-marine',
        proObjective: "Prendre de l'expérience en agence pendant quelques années et travailler en remote à l'étranger",
        quote:'',
        image: "images/photoWilders/dev/ninoJ.jpg",
    },
    {
        firstName: 'Florian',
        lastName: 'Minicelle',
        promo: 'DevWeb',
        birthDate: '05/05/1987',
        github:'https://github.com/FlorianMinic',
        linkedin:'https://www.linkedin.com/in/florian-minicelle-692b9516b/',
        hobbies:'Video games, Making music songs ( content creator)',
        proObjective: "Becomming Web developper",
        quote:"vers l'infini et au delà !",
        image: "images/photoWilders/dev/florianM.jpg",
    },
    {
        firstName: 'Thomas',
        lastName: 'Humbert',
        promo: 'DevWeb',
        birthDate: '17/06/1991',
        github:'https://github.com/H4lfbeard',
        linkedin:'https://www.linkedin.com/in/thomas-humbert-760b37111/',
        hobbies:'Boxe, surf, photographie, musique',
        proObjective: "Devenir developpeur JS",
        quote:"J'adore l'eau, dans 20 / 30 ans il n'y en aura plus !",
        image: "images/photoWilders/dev/thomasH.jpg",
    },
    {
        firstName: 'Raphaël',
        lastName: 'Streiff',
        promo: 'DevWeb',
        birthDate: '29/08/1993',
        github:'https://github.com/Raphael77850',
        linkedin:'https://www.linkedin.com/in/rapha%C3%ABl-streiff-3019a5309/',
        hobbies:'Cuisiner / Jeux-Vidéo / Jardiner',
        proObjective: "Travailler sur une licence de Blizzard-Activision",
        quote:"",
        image: "images/photoWilders/dev/raphS.jpg",
    },
    {
        firstName: 'Nicolas',
        lastName: 'Chiche',
        promo: 'DevWeb',
        birthDate: '20/11/1994',
        github:'https://github.com/nicochnz',
        linkedin:'https://www.linkedin.com/in/nicolas-chiche-79903b2b0/',
        hobbies:'Escalade - Boxe anglaise - Les festoches',
        proObjective: "Devenir un bon dev'",
        quote:"Le temps c'est de l'argent,  pas de temps à perdre !",
        image: "images/photoWilders/dev/nicoC.jpg",
    },
    {
        firstName: 'Mathieu',
        lastName: 'Cahuzac',
        promo: 'DevWeb',
        birthDate: '07/05/1992',
        github:'https://github.com/Cahu07',
        linkedin:'https://www.linkedin.com/in/mathieu-cahuzac-01b335237/',
        hobbies:'Randonnée, Nature',
        proObjective: "developpeur web / cyber sécurité",
        quote:"",
        image: "images/photoWilders/dev/mathieuC.jpg",
    },
    {
        firstName: 'Stephan',
        lastName: 'Queru',
        promo: 'Data',
        birthDate: '02/03/1974',
        github:'',
        linkedin:'https://www.linkedin.com/in/st%C3%A9phan-queru-1a26151b1/',
        hobbies:'Lecture / Sport',
        proObjective: "Diplôme et ensuite boulot.",
        quote:"Seul, on va plus vite. Ensemble, on va plus loin.",
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Cécile',
        lastName: 'Puyol',
        promo: 'DevWeb',
        birthDate: '12/08/1978',
        github:'https://github.com/Ccilpy',
        linkedin:'https://www.linkedin.com/in/cecilepuyol/',
        hobbies:'sorties spectacle ciné danse',
        proObjective: "développeuse web dans une cool boîte dont je partage les valeurs !",
        quote:`"Petit à petit l'oiseau fait son nid."`,
        image: "images/photoWilders/dev/cecileP.jpg",
    },
    {
        firstName: 'Florian',
        lastName: 'Hoarau',
        promo: 'Data',
        birthDate: '22/02/1986',
        github:'',
        linkedin:'',
        hobbies:'Escalade Block',
        proObjective: "Objectif Moulardaire",
        quote:"J'ai la phobie des plannings",
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Thomas',
        lastName: 'Lemallier',
        promo: 'DevWeb',
        birthDate: '13/01/1997',
        github:'https://github.com/ThomasDev4',
        linkedin:'https://www.linkedin.com/in/thomaslemallier',
        hobbies:'jeux vidéos, série film',
        proObjective: "Alternance",
        quote:`"J'adore parler de rien c'est le seul domaine ou j'ai de vagues connaissances"  - Oscar Wilde`,
        image: "images/photoWilders/dev/thomasL.jpg",
    },
    {
        firstName: 'Frédérique',
        lastName: 'Druet',
        promo: 'TSSR',
        birthDate: '27/03/1997',
        github:'https://github.com/FredD27',
        linkedin:'https://www.linkedin.com/in/frederique-druet/',
        hobbies:'musique ciné theatre',
        proObjective: "déesse de la sécu système",
        quote:`Il n'y a pas de bonne ou de mauvaise situation...`,
        image: "images/photoWilders/tssr/fredD.jpg",
    },
    {
        firstName: 'Anthony',
        lastName: 'Vidal',
        promo: 'TSSR',
        birthDate: '23/09/1993',
        github:'https://github.com/Mikantow',
        linkedin:'https://www.linkedin.com/in/anthony-vidal/',
        hobbies:'Foot US',
        proObjective: "Hacker les PC des Dev",
        quote:`Be the change you want to see in the world`,
        image: "images/photoWilders/tssr/anthonyV.jpg",
    },
    {
        firstName: 'Aghiles',
        lastName: 'Belkalem',
        promo: 'DevWeb',
        birthDate: '30/08/1993',
        github:'https://github.com/Aghiles-Belkalem',
        linkedin:'https://linkedin.com/in/aghiles-belkalem-10871323b',
        hobbies:'Dealer',
        proObjective: "devenir Developpeur Web ",
        quote:`l'échec fait partie de la réussite.`,
        image: "images/photoWilders/dev/aghilesB.jpg",
    },
    {
        firstName: 'Manon',
        lastName: 'Labat',
        promo: 'DevWeb',
        birthDate: '10/12/1991',
        github:'https://github.com/Manon879',
        linkedin:'https://linkedin.com/in/aghiles-belkalem-10871323b',
        hobbies:'la cuisine, Jeux Vidéos.',
        proObjective: "Trouver un travail",
        quote:`Quand l'appétit va, tout va !!!!`,
        image: "images/photoWilders/dev/manonL.jpg",
    },
    {
        firstName: 'Pierre',
        lastName: 'de Castelbajac',
        promo: 'DevWeb',
        birthDate: '23/11/1999',
        github:'https://github.com/Pdev33',
        linkedin:'',
        hobbies:'jeux vidéos (gros geek)',
        proObjective: "dev web",
        quote:`a perdu un Kahoot à cause d'une chocolatine ....`,
        image: "images/photoWilders/dev/pierreC.jpg",
    },
    {
        firstName: 'Brieuc',
        lastName: 'Bonnouvrier',
        promo: 'Data',
        birthDate: '29/06/1998',
        github:'',
        linkedin:'https://www.linkedin.com/in/brieuc-bonnouvrier/',
        hobbies:'Course à pied',
        proObjective: "Data analyst - Secteur financier / bancaire",
        quote:`Quand on veut on peut, quand on peut on doit.`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Jordi',
        lastName: 'Garcia Gomà',
        promo: 'Data',
        birthDate: '29/12/1989',
        github:'',
        linkedin:'https://www.linkedin.com/in/jordigarciagoma',
        hobbies:'sport, musique',
        proObjective: "après avoir travaillé 10 ans dans l'enseignement, je souhaite me reconvertir dans la data",
        quote:`j'ai déjà eu des élèves qui m'ont appelé 'papa' en plein cours 😅`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Alexandre',
        lastName: 'Genter',
        promo: 'Data',
        birthDate: '16/02/1994',
        github:'https://github.com/gentalex',
        linkedin:'https://www.linkedin.com/in/alexandre-genter/',
        hobbies:'Crossfit, jeux vidéo, voyage',
        proObjective: "Data Analyst - Gaming - Sport et Banque",
        quote:`J'ai fait un marathon au rameur`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Yann',
        lastName: 'Mac Leod',
        promo: 'Data',
        birthDate: '18/08/1985',
        github:'',
        linkedin:'https://www.linkedin.com/in/yann-mac-leod-385137b5/',
        hobbies:'',
        proObjective: "Reconversion",
        quote:`Euh, sorry ! Ca attendra vendredi :)`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Jérémy',
        lastName: 'Escuer',
        promo: 'Data',
        birthDate: '29/09/1990',
        github:'',
        linkedin:'https://www.linkedin.com/in/j%C3%A9r%C3%A9my-escuer-a64074101/',
        hobbies:'Sport, lecture',
        proObjective: "Trouver un poste de data analyst à la fin de la formation",
        quote:`Un con qui marche va plus loin qu'un intellectuel assis`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Julien',
        lastName: 'Normand',
        promo: 'TSSR',
        birthDate: '15/02/1980',
        github:'https://github.com/julien-Nmd',
        linkedin:'https://www.linkedin.com/in/julien-normand-12976a12b/',
        hobbies:'',
        proObjective: "",
        quote:``,
        image: "images/photoWilders/tssr/julienN.jpg",
    },
    {
        firstName: 'Mindy',
        lastName: 'Setham',
        promo: 'TSSR',
        birthDate: '25/05/1998',
        github:'https://github.com/mindysthm',
        linkedin:'https://www.linkedin.com/in/mindysetham/',
        hobbies:'Pole Dance',
        proObjective: "Travailler dans la cybersécurité",
        quote:``,
        image: "images/photoWilders/tssr/mindyS.jpg",
    },
    {
        firstName: 'Hamza',
        lastName: 'Malki',
        promo: 'TSSR',
        birthDate: '28/03/1990',
        github:'https://github.com/hamza-M-lgtm',
        linkedin:'https://www.linkedin.com/in/hamza-malki-245aba211/',
        hobbies:'cross-fit',
        proObjective: "Travailler dans la cybersécurité",
        quote:`if you can take it you can make it`,
        image: "images/photoWilders/tssr/hamzaM.jpg",
    },
    {
        firstName: 'Sébastien',
        lastName: 'Lazcanotegui',
        promo: 'Data',
        birthDate: '16/01/2000',
        github:'',
        linkedin:'',
        hobbies:'sport, e-sport, voyages, lectures',
        proObjective: "Travailler dans un autre pays",
        quote:`un tuk-tuk ma anarqué 50€`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Roxanne',
        lastName: 'Alezine',
        promo: 'DevWeb',
        birthDate: '07/04/1992',
        github:'https://github.com/Roxanne-Alezine',
        linkedin:'https://www.linkedin.com/in/roxanne-alezine-a76194164/',
        hobbies:"Bientôt le javascript j'espère",
        proObjective: "Trouver un travail et devenir riche",
        quote:``,
        image: "images/photoWilders/dev/roxanneA.jpg",
    },
    {
        firstName: 'Karim',
        lastName: 'Elbaridy',
        promo: 'Data',
        birthDate: '11/07/1992',
        github:'',
        linkedin:'',
        hobbies:"photographie , sport , et analyser des datas :D",
        proObjective: "passer cette formation de data",
        quote:`bah  j'avait une vie tranquille et un jour j'ai décidée de faire une formation de data analyse .`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Aurélien',
        lastName: 'Prat',
        promo: 'Data',
        birthDate: '23/02/1984',
        github:'',
        linkedin:'',
        hobbies:"",
        proObjective: "Devenir Data Analyst",
        quote:`A jamais les premiers !`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Claire',
        lastName: 'Le Guevel',
        promo: 'Data',
        birthDate: '25/04/1978',
        github:'',
        linkedin:'',
        hobbies:"Lecture, golf",
        proObjective: "Devenir data analyst (dans une petite entreprise secteur santé, environnement etc ou en Freelance)",
        quote:`"Dans la vie je ne perds jamais. Soit je gagne soit j'apprends". Nelson Mandela`,
        image: "images/photoWilders/data/phil.png",
    },
    {
        firstName: 'Raphael',
        lastName: 'Barre',
        promo: 'DevWeb',
        birthDate: '06/07/1997',
        github:'https://github.com/Barre-Rapheel',
        linkedin:'https://www.linkedin.com/in/raphael-barre-81b983136?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
        hobbies:"Sport",
        proObjective: "Développeur Web",
        quote:`Dépasser ses limites`,
        image: "images/photoWilders/dev/raphB.jpg",
    },
];
export default studentWild; 